# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:47:18+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, APIKeyQuery, BaseSecurity

from models import (
    BoxScore,
    FieldFormatAllTeamsGetResponse,
    FieldFormatBoxScoresDateGetResponse,
    FieldFormatBoxScoresDeltaDateMinutesGetResponse,
    FieldFormatDfsSlatesByDateDateGetResponse,
    FieldFormatFreeAgentsGetResponse,
    FieldFormatGamesByDateDateGetResponse,
    FieldFormatGamesSeasonGetResponse,
    FieldFormatLinesBySeasonSeasonGetResponse,
    FieldFormatNewsByDateDateGetResponse,
    FieldFormatNewsByPlayerIDPlayeridGetResponse,
    FieldFormatNewsGetResponse,
    FieldFormatPlayerGameStatsByDateDateGetResponse,
    FieldFormatPlayerGameStatsBySeasonSeasonPlayeridNumberofgamesGetResponse,
    FieldFormatPlayerSeasonStatsByTeamSeasonTeamGetResponse,
    FieldFormatPlayerSeasonStatsSeasonGetResponse,
    FieldFormatPlayersGetResponse,
    FieldFormatPlayersTeamGetResponse,
    FieldFormatStadiumsGetResponse,
    FieldFormatStandingsSeasonGetResponse,
    FieldFormatTeamGameStatsByDateDateGetResponse,
    FieldFormatTeamGameStatsBySeasonSeasonTeamidNumberofgamesGetResponse,
    FieldFormatTeamSeasonStatsSeasonGetResponse,
    FieldFormatTeamsGetResponse,
    FieldFormatTeamStatsAllowedByPositionSeasonGetResponse,
    Format,
    Format23,
    Format24,
    Player,
    PlayerGame,
    PlayerSeason,
    Season,
)

app = MCPProxy(
    contact={'x-twitter': 'nfldata'},
    title='NHL v3 Stats',
    version='1.0',
    servers=[
        {'url': 'http://azure-api.sportsdata.io/v3/nhl/stats'},
        {'url': 'https://azure-api.sportsdata.io/v3/nhl/stats'},
    ],
)


@app.get(
    '/{format}/AllTeams',
    tags=['team_information'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def teams_all(format: Format = 'XML'):
    """
    Teams (All)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/AreAnyGamesInProgress',
    description=""" Returns <code>true</code> if there is at least one game being played at the time of the request or <code>false</code> if there are none. """,
    tags=['game_metrics', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def are_games_in_progress(format: Format = 'XML'):
    """
    Are Games In Progress
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/BoxScore/{gameid}',
    tags=['game_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def box_score(format: Format = 'XML', gameid: str = ...):
    """
    Box Score
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/BoxScores/{date}',
    tags=['game_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def box_scores_by_date(format: Format = 'XML', date: str = ...):
    """
    Box Scores by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/BoxScoresDelta/{date}/{minutes}',
    tags=['game_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def box_scores_by_date_delta(
    format: Format = 'XML', date: str = ..., minutes: str = ...
):
    """
    Box Scores by Date Delta
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/CurrentSeason',
    tags=['season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def current_season(format: Format = 'XML'):
    """
    Current Season
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/DfsSlatesByDate/{date}',
    tags=['dfs_slates_management'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def dfs_slates_by_date(format: Format = 'XML', date: str = ...):
    """
    DFS Slates by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/FreeAgents',
    tags=['player_registry', 'player_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_details_by_free_agent(format: Format = 'XML'):
    """
    Player Details by Free Agent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/Games/{season}',
    tags=['team_information', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def schedules(format: Format = 'XML', season: str = ...):
    """
    Schedules
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/GamesByDate/{date}',
    tags=['game_metrics', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def games_by_date(format: Format = 'XML', date: str = ...):
    """
    Games by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/LinesBySeason/{season}',
    tags=['line_combos', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def line_combinations_by_season(format: Format = 'XML', season: str = ...):
    """
    Line Combinations by Season
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/News',
    tags=['news_feed'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def news(format: Format = 'XML'):
    """
    News
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/NewsByDate/{date}',
    tags=['news_feed'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def news_by_date(format: Format = 'XML', date: str = ...):
    """
    News by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/NewsByPlayerID/{playerid}',
    tags=['news_feed', 'player_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def news_by_player(format: Format = 'XML', playerid: str = ...):
    """
    News by Player
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/Player/{playerid}',
    tags=['player_metrics', 'player_registry'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_details_by_player(format: Format = 'XML', playerid: str = ...):
    """
    Player Details by Player
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameStatsByDate/{date}',
    tags=['game_metrics', 'player_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_game_stats_by_date(format: Format = 'XML', date: str = ...):
    """
    Player Game Stats by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameStatsByPlayer/{date}/{playerid}',
    tags=['player_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_game_stats_by_player(
    format: Format = 'XML', date: str = ..., playerid: str = ...
):
    """
    Player Game Stats by Player
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerGameStatsBySeason/{season}/{playerid}/{numberofgames}',
    tags=['game_metrics', 'player_metrics', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_game_logs_by_season(
    format: Format, season: str = ..., playerid: str = ..., numberofgames: str = ...
):
    """
    Player Game Logs By Season
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerSeasonStats/{season}',
    tags=['player_metrics', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_season_stats(format: Format = 'XML', season: str = ...):
    """
    Player Season Stats
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerSeasonStatsByPlayer/{season}/{playerid}',
    tags=['player_metrics', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_season_stats_by_player(
    format: Format = 'XML', season: str = ..., playerid: str = ...
):
    """
    Player Season Stats By Player
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/PlayerSeasonStatsByTeam/{season}/{team}',
    tags=['team_information', 'player_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_season_stats_by_team(
    format: Format = 'XML', season: str = ..., team: str = ...
):
    """
    Player Season Stats by Team
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/Players',
    tags=['player_metrics', 'player_registry'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def player_details_by_active(format: Format = 'XML'):
    """
    Player Details by Active
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/Players/{team}',
    tags=['team_information', 'player_metrics'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def players_by_team(format: Format = 'XML', team: str = ...):
    """
    Players by Team
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/Stadiums',
    tags=['stadium_data'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def stadiums(format: Format23 = 'xml'):
    """
    Stadiums
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/Standings/{season}',
    tags=['season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def standings(format: Format24 = 'XML', season: str = ...):
    """
    Standings
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/TeamGameStatsByDate/{date}',
    tags=['game_metrics', 'team_information'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def team_game_stats_by_date(format: Format24 = 'XML', date: str = ...):
    """
    Team Game Stats by Date
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/TeamGameStatsBySeason/{season}/{teamid}/{numberofgames}',
    description=""" Game by game log of total team statistics. """,
    tags=['team_information', 'game_metrics', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def team_game_logs_by_season(
    format: Format24, season: str = ..., teamid: str = ..., numberofgames: str = ...
):
    """
    Team Game Logs By Season
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/TeamSeasonStats/{season}',
    tags=['team_information', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def team_season_stats(format: Format24 = 'XML', season: str = ...):
    """
    Team Season Stats
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/TeamStatsAllowedByPosition/{season}',
    tags=['team_information', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def team_stats_allowed_by_position(format: Format24 = 'XML', season: str = ...):
    """
    Team Stats Allowed by Position
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{format}/teams',
    tags=['team_information', 'season_overview'],
    security=[
        APIKeyHeader(name="Ocp-Apim-Subscription-Key"),
        APIKeyQuery(name="key"),
    ],
)
def teams_active(format: Format24 = 'XML'):
    """
    Teams (Active)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
