# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:47:18+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class News(BaseModel):
    Content: Optional[str] = None
    NewsID: Optional[int] = None
    PlayerID: Optional[int] = None
    Source: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    TermsOfUse: Optional[str] = None
    Title: Optional[str] = None
    Updated: Optional[str] = None
    Url: Optional[str] = None


class OpponentSeason(BaseModel):
    Assists: Optional[float] = None
    BenchPenaltyMinutes: Optional[float] = None
    Blocks: Optional[float] = None
    EmptyNetGoals: Optional[float] = None
    FaceoffsLost: Optional[float] = None
    FaceoffsWon: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Games: Optional[int] = None
    Giveaways: Optional[float] = None
    GlobalTeamID: Optional[int] = None
    Goals: Optional[float] = None
    GoaltendingGoalsAgainst: Optional[float] = None
    GoaltendingLosses: Optional[float] = None
    GoaltendingMinutes: Optional[int] = None
    GoaltendingOvertimeLosses: Optional[float] = None
    GoaltendingSaves: Optional[float] = None
    GoaltendingSeconds: Optional[int] = None
    GoaltendingShotsAgainst: Optional[float] = None
    GoaltendingShutouts: Optional[float] = None
    GoaltendingWins: Optional[float] = None
    HatTricks: Optional[float] = None
    Hits: Optional[float] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OpponentPosition: Optional[str] = None
    OvertimeLosses: Optional[int] = None
    PenaltyMinutes: Optional[float] = None
    PlusMinus: Optional[float] = None
    PowerPlayAssists: Optional[float] = None
    PowerPlayGoals: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Shifts: Optional[float] = None
    ShootoutGoals: Optional[float] = None
    ShortHandedAssists: Optional[float] = None
    ShortHandedGoals: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Takeaways: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Updated: Optional[str] = None
    Wins: Optional[int] = None


class Penalty(BaseModel):
    BenchPenaltyServedByPlayerID: Optional[int] = None
    Description: Optional[str] = None
    DrawnByPlayerID: Optional[int] = None
    DrawnByTeamID: Optional[int] = None
    IsBenchPenalty: Optional[bool] = None
    PenalizedPlayerID: Optional[int] = None
    PenalizedTeamID: Optional[int] = None
    PenaltyID: Optional[int] = None
    PenaltyMinutes: Optional[int] = None
    PeriodID: Optional[int] = None
    Sequence: Optional[int] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None


class Play(BaseModel):
    AwayTeamScore: Optional[int] = None
    Category: Optional[str] = None
    ClockMinutes: Optional[int] = None
    ClockSeconds: Optional[int] = None
    Created: Optional[str] = None
    Description: Optional[str] = None
    FirstAssistedByPlayerID: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpposingPlayerID: Optional[int] = None
    PeriodID: Optional[int] = None
    PeriodName: Optional[str] = None
    PlayID: Optional[int] = None
    PlayerID: Optional[int] = None
    PowerPlayTeam: Optional[str] = None
    PowerPlayTeamID: Optional[int] = None
    SecondAssistedByPlayerID: Optional[int] = None
    Sequence: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Type: Optional[str] = None
    Updated: Optional[str] = None


class Player(BaseModel):
    BirthCity: Optional[str] = None
    BirthDate: Optional[str] = None
    BirthState: Optional[str] = None
    Catches: Optional[str] = None
    DepthChartOrder: Optional[int] = None
    DepthChartPosition: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[int] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Jersey: Optional[int] = None
    LastName: Optional[str] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    Shoots: Optional[str] = None
    SportRadarPlayerID: Optional[str] = None
    SportsDirectPlayerID: Optional[int] = None
    StatsPlayerID: Optional[int] = None
    Status: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None
    XmlTeamPlayerID: Optional[int] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class PlayerGame(BaseModel):
    Assists: Optional[float] = None
    BenchPenaltyMinutes: Optional[float] = None
    Blocks: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    EmptyNetGoals: Optional[float] = None
    FaceoffsLost: Optional[float] = None
    FaceoffsWon: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyDataSalary: Optional[int] = None
    FantasyDraftPosition: Optional[str] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    Giveaways: Optional[float] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Goals: Optional[float] = None
    GoaltendingGoalsAgainst: Optional[float] = None
    GoaltendingLosses: Optional[float] = None
    GoaltendingMinutes: Optional[int] = None
    GoaltendingOvertimeLosses: Optional[float] = None
    GoaltendingSaves: Optional[float] = None
    GoaltendingSeconds: Optional[int] = None
    GoaltendingShotsAgainst: Optional[float] = None
    GoaltendingShutouts: Optional[float] = None
    GoaltendingWins: Optional[float] = None
    HatTricks: Optional[float] = None
    Hits: Optional[float] = None
    HomeOrAway: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsGameOver: Optional[bool] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    PenaltyMinutes: Optional[float] = None
    PlayerID: Optional[int] = None
    PlusMinus: Optional[float] = None
    Position: Optional[str] = None
    PowerPlayAssists: Optional[float] = None
    PowerPlayGoals: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Shifts: Optional[float] = None
    ShootoutGoals: Optional[float] = None
    ShortHandedAssists: Optional[float] = None
    ShortHandedGoals: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Takeaways: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Updated: Optional[str] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None


class PlayerLine(BaseModel):
    LineNumber: Optional[int] = None
    LineType: Optional[str] = None
    Name: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    Shoots: Optional[str] = None


class PlayerSeason(BaseModel):
    Assists: Optional[float] = None
    BenchPenaltyMinutes: Optional[float] = None
    Blocks: Optional[float] = None
    EmptyNetGoals: Optional[float] = None
    FaceoffsLost: Optional[float] = None
    FaceoffsWon: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Games: Optional[int] = None
    Giveaways: Optional[float] = None
    GlobalTeamID: Optional[int] = None
    Goals: Optional[float] = None
    GoaltendingGoalsAgainst: Optional[float] = None
    GoaltendingLosses: Optional[float] = None
    GoaltendingMinutes: Optional[int] = None
    GoaltendingOvertimeLosses: Optional[float] = None
    GoaltendingSaves: Optional[float] = None
    GoaltendingSeconds: Optional[int] = None
    GoaltendingShotsAgainst: Optional[float] = None
    GoaltendingShutouts: Optional[float] = None
    GoaltendingWins: Optional[float] = None
    HatTricks: Optional[float] = None
    Hits: Optional[float] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    PenaltyMinutes: Optional[float] = None
    PlayerID: Optional[int] = None
    PlusMinus: Optional[float] = None
    Position: Optional[str] = None
    PowerPlayAssists: Optional[float] = None
    PowerPlayGoals: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Shifts: Optional[float] = None
    ShootoutGoals: Optional[float] = None
    ShortHandedAssists: Optional[float] = None
    ShortHandedGoals: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Takeaways: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Updated: Optional[str] = None


class ScoringPlay(BaseModel):
    AllowedByTeamID: Optional[int] = None
    AssistedByPlayerID1: Optional[int] = None
    AssistedByPlayerID2: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    EmptyNet: Optional[bool] = None
    HomeTeamScore: Optional[int] = None
    PeriodID: Optional[int] = None
    PowerPlay: Optional[bool] = None
    ScoredByPlayerID: Optional[int] = None
    ScoredByTeamID: Optional[int] = None
    ScoringPlayID: Optional[int] = None
    Sequence: Optional[int] = None
    ShortHanded: Optional[bool] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None


class Season(BaseModel):
    ApiSeason: Optional[str] = None
    Description: Optional[str] = None
    EndYear: Optional[int] = None
    PostSeasonStartDate: Optional[str] = None
    RegularSeasonStartDate: Optional[str] = None
    Season: Optional[int] = None
    SeasonType: Optional[str] = None
    StartYear: Optional[int] = None


class Series(BaseModel):
    AwayTeamWins: Optional[int] = None
    GameNumber: Optional[int] = None
    HomeTeamWins: Optional[int] = None
    MaxLength: Optional[int] = None


class Stadium(BaseModel):
    Active: Optional[bool] = None
    Address: Optional[str] = None
    Capacity: Optional[int] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    Name: Optional[str] = None
    StadiumID: Optional[int] = None
    State: Optional[str] = None
    Zip: Optional[str] = None


class Standing(BaseModel):
    City: Optional[str] = None
    Conference: Optional[str] = None
    ConferenceLosses: Optional[int] = None
    ConferenceRank: Optional[int] = None
    ConferenceWins: Optional[int] = None
    Division: Optional[str] = None
    DivisionLosses: Optional[int] = None
    DivisionRank: Optional[int] = None
    DivisionWins: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Key: Optional[str] = None
    Losses: Optional[int] = None
    Name: Optional[str] = None
    OvertimeLosses: Optional[int] = None
    Percentage: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShutoutWins: Optional[int] = None
    TeamID: Optional[int] = None
    Wins: Optional[int] = None


class Team(BaseModel):
    Active: Optional[bool] = None
    City: Optional[str] = None
    Conference: Optional[str] = None
    Division: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Key: Optional[str] = None
    Name: Optional[str] = None
    PrimaryColor: Optional[str] = None
    QuaternaryColor: Optional[str] = None
    SecondaryColor: Optional[str] = None
    StadiumID: Optional[int] = None
    TeamID: Optional[int] = None
    TertiaryColor: Optional[str] = None
    WikipediaLogoUrl: Optional[str] = None
    WikipediaWordMarkUrl: Optional[str] = None


class TeamGame(BaseModel):
    Assists: Optional[float] = None
    BenchPenaltyMinutes: Optional[float] = None
    Blocks: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    EmptyNetGoals: Optional[float] = None
    FaceoffsLost: Optional[float] = None
    FaceoffsWon: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    Giveaways: Optional[float] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Goals: Optional[float] = None
    GoaltendingGoalsAgainst: Optional[float] = None
    GoaltendingLosses: Optional[float] = None
    GoaltendingMinutes: Optional[int] = None
    GoaltendingOvertimeLosses: Optional[float] = None
    GoaltendingSaves: Optional[float] = None
    GoaltendingSeconds: Optional[int] = None
    GoaltendingShotsAgainst: Optional[float] = None
    GoaltendingShutouts: Optional[float] = None
    GoaltendingWins: Optional[float] = None
    HatTricks: Optional[float] = None
    Hits: Optional[float] = None
    HomeOrAway: Optional[str] = None
    IsGameOver: Optional[bool] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OvertimeLosses: Optional[int] = None
    PenaltyMinutes: Optional[float] = None
    PlusMinus: Optional[float] = None
    PowerPlayAssists: Optional[float] = None
    PowerPlayGoals: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Shifts: Optional[float] = None
    ShootoutGoals: Optional[float] = None
    ShortHandedAssists: Optional[float] = None
    ShortHandedGoals: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Takeaways: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Updated: Optional[str] = None
    Wins: Optional[int] = None


class TeamLine(BaseModel):
    EvenStrengthLines: Optional[List[PlayerLine]] = None
    FullName: Optional[str] = None
    Key: Optional[str] = None
    PowerPlayLines: Optional[List[PlayerLine]] = None
    TeamID: Optional[int] = None


class TeamSeason(BaseModel):
    Assists: Optional[float] = None
    BenchPenaltyMinutes: Optional[float] = None
    Blocks: Optional[float] = None
    EmptyNetGoals: Optional[float] = None
    FaceoffsLost: Optional[float] = None
    FaceoffsWon: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Games: Optional[int] = None
    Giveaways: Optional[float] = None
    GlobalTeamID: Optional[int] = None
    Goals: Optional[float] = None
    GoaltendingGoalsAgainst: Optional[float] = None
    GoaltendingLosses: Optional[float] = None
    GoaltendingMinutes: Optional[int] = None
    GoaltendingOvertimeLosses: Optional[float] = None
    GoaltendingSaves: Optional[float] = None
    GoaltendingSeconds: Optional[int] = None
    GoaltendingShotsAgainst: Optional[float] = None
    GoaltendingShutouts: Optional[float] = None
    GoaltendingWins: Optional[float] = None
    HatTricks: Optional[float] = None
    Hits: Optional[float] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OpponentPosition: Optional[str] = None
    OpponentStat: Optional[OpponentSeason] = None
    OvertimeLosses: Optional[int] = None
    PenaltyMinutes: Optional[float] = None
    PlusMinus: Optional[float] = None
    PowerPlayAssists: Optional[float] = None
    PowerPlayGoals: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Seconds: Optional[int] = None
    Shifts: Optional[float] = None
    ShootoutGoals: Optional[float] = None
    ShortHandedAssists: Optional[float] = None
    ShortHandedGoals: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    Takeaways: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Updated: Optional[str] = None
    Wins: Optional[int] = None


class FieldFormatAllTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatFreeAgentsGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatLinesBySeasonSeasonGetResponse(RootModel[List[TeamLine]]):
    root: List[TeamLine]


class FieldFormatNewsGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByDateDateGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByPlayerIDPlayeridGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatPlayerGameStatsByDateDateGetResponse(RootModel[List[PlayerGame]]):
    root: List[PlayerGame]


class FieldFormatPlayerGameStatsBySeasonSeasonPlayeridNumberofgamesGetResponse(
    RootModel[List[PlayerGame]]
):
    root: List[PlayerGame]


class FieldFormatPlayerSeasonStatsSeasonGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonStatsByTeamSeasonTeamGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatPlayersTeamGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatStadiumsGetResponse(RootModel[List[Stadium]]):
    root: List[Stadium]


class Format23(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatStandingsSeasonGetResponse(RootModel[List[Standing]]):
    root: List[Standing]


class Format24(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatTeamGameStatsByDateDateGetResponse(RootModel[List[TeamGame]]):
    root: List[TeamGame]


class FieldFormatTeamGameStatsBySeasonSeasonTeamidNumberofgamesGetResponse(
    RootModel[List[TeamGame]]
):
    root: List[TeamGame]


class FieldFormatTeamSeasonStatsSeasonGetResponse(RootModel[List[TeamSeason]]):
    root: List[TeamSeason]


class FieldFormatTeamStatsAllowedByPositionSeasonGetResponse(
    RootModel[List[TeamSeason]]
):
    root: List[TeamSeason]


class FieldFormatTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Period(BaseModel):
    AwayScore: Optional[int] = None
    GameID: Optional[int] = None
    HomeScore: Optional[int] = None
    Name: Optional[str] = None
    Penalties: Optional[List[Penalty]] = None
    PeriodID: Optional[int] = None
    ScoringPlays: Optional[List[ScoringPlay]] = None


class Game(BaseModel):
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    Channel: Optional[str] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    IsClosed: Optional[bool] = None
    LastPlay: Optional[str] = None
    NeutralVenue: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    Period: Optional[str] = None
    Periods: Optional[List[Period]] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SeriesInfo: Optional[Series] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None


class FieldFormatGamesSeasonGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatGamesByDateDateGetResponse(RootModel[List[Game]]):
    root: List[Game]


class BoxScore(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    Periods: Optional[List[Period]] = None
    PlayerGames: Optional[List[PlayerGame]] = None
    ShootoutPlays: Optional[List[Play]] = None
    TeamGames: Optional[List[TeamGame]] = None


class DfsSlateGame(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class FieldFormatBoxScoresDateGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class FieldFormatBoxScoresDeltaDateMinutesGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class DfsSlate(BaseModel):
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]
